import 'dart:convert';
import 'dart:io';

import 'pipeline.dart';

Map<String, dynamic>? loadResult(String toolDir, String exercise) {
  final file = File('$toolDir/results/${slugFor(exercise)}.json');
  if (!file.existsSync()) return null;
  final json = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  return json['pick'] == null ? null : json;
}

/// Emits `lib/core/constants/exercise_videos.g.dart`: a const name→URL map
/// for the built-in exercise library, keyed by the canonical English names
/// from exercises.csv (the app's identity keys — byte-for-byte, never
/// translated). Exercises without a curated pick are omitted — the exercise
/// info dialog already renders a "no video" state — and listed in a trailing
/// comment so coverage gaps stay visible.
///
/// This file is the only app-specific piece of the curator — to reuse the
/// tool in another app, replace this emitter.
String emitDart(String toolDir, {DateTime? now}) {
  final entries = loadConfig(toolDir);
  final seen = <String>{};
  final curated = <String, String>{};
  final missing = <String>[];
  for (final e in entries) {
    if (!seen.add(e.exercise)) continue;
    final result = loadResult(toolDir, e.exercise);
    if (result == null) {
      missing.add(e.exercise);
    } else {
      curated[e.exercise] = result['pick']['videoId'] as String;
    }
  }

  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/video_curator — do not edit by hand.')
    ..writeln(
      '// Regenerate: dart run bin/curate.dart --emit  (from tool/video_curator)',
    )
    ..writeln('// Generated: ${(now ?? DateTime.now()).toIso8601String()}')
    ..writeln()
    ..writeln(
      '/// Curated YouTube videos for built-in exercises, keyed by the canonical',
    )
    ..writeln('/// English exercise name from exercises.csv.')
    ..writeln('const Map<String, String> generatedExerciseVideos = {');
  curated.forEach((name, videoId) {
    buffer.writeln(
      "  '${_escape(name)}': 'https://www.youtube.com/watch?v=$videoId',",
    );
  });
  buffer.writeln('};');

  if (missing.isNotEmpty) {
    buffer
      ..writeln()
      ..writeln('// Not curated yet (${missing.length}):');
    for (final name in missing) {
      buffer.writeln('// - $name');
    }
  }
  return buffer.toString();
}

/// Escapes a value for use inside a single-quoted Dart string literal.
String _escape(String s) =>
    s.replaceAll(r'\', r'\\').replaceAll(r'$', r'\$').replaceAll("'", r"\'");
